name: Deploy para produção

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy na VPS
        uses: appleboy/ssh-action@2ead5e36573f08b82fbfce1504f1a4b05a647c6f # v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          fingerprint: "SHA256:sIxpOfQWjfahhEP2aH8u0srCb6pP5POnme/92E/recI"
          script: echo "deploy" # comando forçado no servidor ignora isto e corre sempre /usr/local/bin/deploy-colo
